name: 'Code Quality With Code Climate'

on:
  workflow_call:
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL:
        required: true
jobs:
  code-quality:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Use Code Climate CLI
        run: |
          docker pull codeclimate/codeclimate
          docker run --tty --rm \
            --env CODECLIMATE_CODE="$PWD" \
            --volume "$PWD":/code \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            --volume /tmp/cc:/tmp/cc \
            codeclimate/codeclimate analyze
        continue-on-error: true

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: code quality
      #     path: code-quality-${{ github.run_id }}-${{ github.run_number }}.html
      #     overwrite: true
      
      - name: Notify Google Chat
        if: ${{ always() }}
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          jobStatus: ${{ job.status }}
          title: 'Code quality'
          subtitle: ${{ github.event.pull_request.head.ref }}