name: 'Create Load Test Infra'

on: 
  workflow_call:
    secrets:
      WORKLOAD_IDENTITY_PROVIDER:
        required: true
      SERVICE_ACCOUNT:
        required: true
      CLOUD_REGISTRY:
        required: true
      SERVICE:
        required: true
      PORT:
        required: true
      GOOGLE_CHAT_WEBHOOK_URL:
        required: true
      IMAGE_TAG:
        required: true
      DATASET_TEST:

jobs:
  create-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
      
      - name: 'Build & Push Image'
        run: |
          gcloud auth configure-docker us-east4-docker.pkg.dev
          docker build -t ${{ secrets.CLOUD_REGISTRY }}:${{ secrets.IMAGE_TAG }} .
          docker push ${{ secrets.CLOUD_REGISTRY }}:${{ secrets.IMAGE_TAG }}
      
      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy ${{ secrets.SERVICE }}-${{ github.ref_name }} \
            --image ${{ secrets.CLOUD_REGISTRY }}:${{ secrets.IMAGE_TAG }} \
            --region us-east4 \
            --platform managed \
            --allow-unauthenticated \
            --update-secrets=ENV=${{ secrets.SERVICE }}:latest \
            --port ${{ secrets.PORT }} \
            --memory 128Mi \
            --set-env-vars=DB_DATASET_TEST=${{ secrets.DATASET_TEST }} \
            --service-account=${{ secrets.SERVICE_ACCOUNT }}
            
      - name: Set SERVICE_URL environment variable
        id: set_service_url
        run: |
          SERVICE_URL=$(gcloud run services describe ${{ secrets.SERVICE }}-${{ github.ref_name }} \
          --region us-east4 \
          --format "value(status.url)")
          
          echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV
          echo "::set-output name=service_url::$SERVICE_URL"
          echo "SERVICE_URL=$SERVICE_URL" > url.txt
  
      - name: Notify Google Chat
        if: ${{ always() }}
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          jobStatus: ${{ job.status }}
          title: ${{ github.workflow }}
          subtitle: ${{ github.event.pull_request.head.ref }}
          additionalSections: '[{"header": "Reviewer App Access", "collapsible": true, "widgets": [{"decoratedText": {"startIcon": {"knownIcon": "STAR"},"text": "${{ steps.set_service_url.outputs.service_url }}" }}] }]'
      