name: Dependency-Check

on:
  workflow_call:
    secrets:
      GOOGLE_CHAT_WEBHOOK_URL:
        required: true

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.24.2
          go-package: ./...

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: dependency scanner
      #     path: vuln-check-${{ github.run_id }}-${{ github.run_number }}.txt
      #     if-no-files-found: ignore
      
      - name: Notify Google Chat
        if: ${{ always() }}
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          jobStatus: ${{ job.status }}
          title: 'Dependency-Check'
          subtitle: ${{ github.event.pull_request.head.ref }}
